/**
 * Core type definitions for @washi-ui/core
 * @module types
 */

/**
 * Adapter interface for persisting comments.
 * Implement this interface to connect Washi to your storage backend.
 *
 * @example
 * ```typescript
 * class MyAdapter implements WashiAdapter {
 *   async save(comment: Comment) {
 *     await fetch('/api/comments', {
 *       method: 'POST',
 *       body: JSON.stringify(comment)
 *     });
 *   }
 *
 *   async load() {
 *     const res = await fetch('/api/comments');
 *     return res.json();
 *   }
 *
 *   async update(id: string, updates: Partial<Comment>) {
 *     await fetch(`/api/comments/${id}`, {
 *       method: 'PATCH',
 *       body: JSON.stringify(updates)
 *     });
 *   }
 *
 *   async delete(id: string) {
 *     await fetch(`/api/comments/${id}`, { method: 'DELETE' });
 *   }
 * }
 * ```
 */
export interface WashiAdapter {
  /**
   * Save a new comment to storage.
   * @param comment - The comment to save
   */
  save(comment: Comment): Promise<void>;

  /**
   * Load all comments from storage.
   * @returns Array of all stored comments
   */
  load(): Promise<Comment[]>;

  /**
   * Update an existing comment with partial data.
   * @param id - The comment ID to update
   * @param updates - Partial comment data to merge
   */
  update(id: string, updates: Partial<Comment>): Promise<void>;

  /**
   * Delete a comment from storage.
   * @param id - The comment ID to delete
   */
  delete(id: string): Promise<void>;
}

/**
 * Represents a single comment/annotation.
 */
export interface Comment {
  /** Unique identifier for the comment, generated by the library. */
  id: string;

  /** Horizontal position as percentage (0-100) of content width */
  x: number;

  /** Vertical position as percentage (0-100) of content height */
  y: number;

  /** The comment text content */
  text: string;

  /** Whether the comment has been resolved */
  resolved?: boolean;

  /** Unix timestamp (milliseconds) when the comment was created */
  createdAt: number;

  /** Pin color (defaults to first color in palette) */
  color?: string;
}

/**
 * Input type for creating a new comment.
 * The library generates `id` and `createdAt` automatically.
 */
export interface NewComment {
  /** Horizontal position as percentage (0-100) of content width */
  x: number;

  /** Vertical position as percentage (0-100) of content height */
  y: number;

  /** The comment text content */
  text: string;

  /** Optional pin color */
  color?: string;
}

/**
 * Interaction mode for the comment system.
 * - 'view': Pins are clickable, but overlay doesn't capture clicks
 * - 'annotate': Clicking on overlay emits coordinates for new comments
 */
export type WashiMode = 'view' | 'annotate';

/**
 * Event names that can be subscribed to via washi.on()
 */
export type WashiEvent =
  | 'pin:placed'
  | 'comment:created'
  | 'comment:updated'
  | 'comment:deleted'
  | 'comment:clicked'
  | 'mode:changed'
  | 'error';

/**
 * Options for mounting the Washi instance.
 */
export interface MountOptions {
  /**
   * When true, prevents switching to annotate mode.
   * Useful for view-only scenarios.
   */
  readOnly?: boolean;

  /**
   * When true, suppresses the built-in pin dialog on pin click.
   * Use this when rendering a custom popover via the `comment:clicked` event.
   */
  disableBuiltinDialog?: boolean;
}

/**
 * Event payload when overlay is clicked in annotate mode.
 * Contains coordinates where the user clicked.
 */
export interface PinPlacedEvent {
  /** X position as percentage (0-100) */
  x: number;
  /** Y position as percentage (0-100) */
  y: number;
}

/**
 * Event payload when a comment is updated.
 */
export interface CommentUpdatedEvent {
  /** ID of the updated comment */
  id: string;
  /** The partial updates that were applied */
  updates: Partial<Comment>;
}

/**
 * Event payload when a comment is deleted.
 */
export interface CommentDeletedEvent {
  /** ID of the deleted comment */
  id: string;
}

/**
 * Event payload when a pin is clicked.
 */
export interface CommentClickedEvent {
  /** The full comment object that was clicked */
  comment: Comment;
}

/**
 * Event payload when mode changes.
 */
export interface ModeChangedEvent {
  /** The new mode */
  mode: WashiMode;
  /** The previous mode before the change */
  previousMode: WashiMode;
}

/**
 * Event payload for error events.
 */
export interface ErrorEvent {
  /** Error type identifier */
  type: string;
  /** Human-readable error message */
  message: string;
  /** Original error object if available */
  error?: Error;
}
